name: latlong
description: Lightweight library for common latitude and longitude calculation
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-latlong

version: 0.6.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  logging: ^0.11.4
  console_log_handler: ^1.1.6
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  validate: ^1.0.0

  intl: ^0.16.1

dev_dependencies:
  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any
